farmerHead:
  growRadius: 3 # радиус действия шара
  growCooldownSeconds: 30 # время ожидания перед повторным использованием
  displayName: "&d&lШар Огородника" # название предмета
  lore: # описание
    - ""
messages:
  cooldown:
    wait: "&cПожалуйста, подождите {time} секунд перед повторным использованием." # {time} - время до использования